"@startuml Planning architecture"
skinparam componentStyle uml1

actor Менеджер as Manager
actor Клиент as Client
actor Аналитик as BI

package Authorization {
    component Auth
    database Redis as redis2
    database Postgres as postgres2
}

package Proxy-server {
    rectangle nginx {
        component router as router1
        component router as router2
    }
}

package Admin-panel {
    component DjangoWebBackend as django
    database Postgres as postgres1
}

package FullTextSearch {
    cloud {
        component ETLprocess as etl
    }
    database ElasticSearch
}

package Movie-search {
    component FastapiWebBackend as fastapi
    database Redis as redis1
}

rectangle Планируемая_архитектура #LightBlue{
    package UGC {
        component BigDataBackend as bigdata
        database Kafka
        database ClickHouse as click
        cloud {
            component ETLprocess as etl2
        }
    }
}

Manager -[hidden]-> Client
router1 -[hidden]-> router2
fastapi -d-> Auth: Проверка разрешений\n пользователя
Manager -> router1
Client -l-> router2
router1 -> django: Добавление/редактирование\n информации о фильме
django -> postgres1
postgres1 -r-> etl
etl -d-> ElasticSearch
router2 -l-> fastapi: Поиск по фильмам/актерам\n/жанрам
router2 -l-> fastapi: Просмотр фильмов
fastapi --> redis1
fastapi -> ElasticSearch
router2 -> Auth: Регистрация/логин\n/логаут/изменение данных
Auth -d-> postgres2
Auth -> redis2
router2 -d-> bigdata: Временные метки\n фильмов
router2 -d-> bigdata: Отзывы, комментарии\n пользователя
bigdata -d-> Kafka
Kafka -d-> etl2
etl2 -> click
BI -> click: Анализ\n предпочтений\n пользователя

@enduml 