FROM python:3.10-slim-bullseye

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/code

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt \
    && rm -rf /var/lib/apt/lists/* /tmp/*

COPY ["etl_kafka_mongo.py", "logging_config.py", "settings.py", "./"]

CMD [ "python3", "etl_kafka_mongo.py"]
